[workspace]
members = ["hotham", "hotham-simulator", "examples/simple-scene", "examples/crab-saber", "benchmarks/stress-test"]

# Make performance critical packages compile with optimizations
[profile.dev.package.rapier3d]
opt-level = 3

[profile.dev.package.gltf]
opt-level = 3

[profile.dev.package.image]
opt-level = 3

[profile.dev.package.symphonia]
opt-level = 3
