[package]
authors = ["Kane Rogers <kane.m.rogers@gmail.com>"]
build = "build.rs"
edition = "2018"
name = "hotham"
version = "0.1.0"

[build-dependencies]
shaderc = "0.7"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
approx = "0.5"
ash = "0.32"
console = "0.14"
crossbeam = "0.8.1"
ctrlc = {version = "3", features = ["termination"]}
gltf = "0.16"
itertools = "0.10.0"
kira = "0.5.3"
legion = "0.4"
libktx-rs = "0.2"
memoffset = "0.5.1"
mint = "0.5.6"
nalgebra = {features = ["convert-mint", "serde-serialize"], version = "0.29.0"}
openxr = {features = ["loaded", "mint"], git = "https://github.com/Ralith/openxrs", rev = "8c23c05ce8395a58910d0e90ce6ac799b1013083"}
rand = "0.8"
rapier3d = "0.11"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
thiserror = "1.0"
winit = "0.24"

[target.'cfg(target_os = "android")'.dependencies]
jni = "0.18.0"
ndk = "0.3.0"
ndk-glue = "0.3"

[dev-dependencies.criterion]
features = ["html_reports"]
version = "0.3"

# [[bench]]
# harness = false
# name = "model_loading"

[[bench]]
harness = false
name = "transform_system"
