[package]
authors = ["Kane Rogers <kane.m.rogers@gmail.com>"]
build = "build.rs"
edition = "2018"
name = "hotham"
version = "0.1.0"

[build-dependencies]
shaderc = "0.7"

[dependencies]
anyhow = "1.0"
ash = "0.33.2"
console = "0.14"
crossbeam = "0.8.1"
ctrlc = {version = "3", features = ["termination"]}
egui = "0.15"
gltf = {version = "0.16", features = ["KHR_materials_pbrSpecularGlossiness"]}
hotham-debug-server = {path = "../hotham-debug-server"}
image = "0.23"
itertools = "0.10.0"
legion = "0.4"
libktx-rs = "0.2.3"
memoffset = "0.5.1"
mint = "0.5.6"
nalgebra = {features = ["convert-mint", "serde-serialize"], version = "0.29.0"}
oddio = "0.5"
openxr = {features = ["loaded", "mint"], version = "0.15.5"}
rand = "0.8"
rapier3d = "0.11.1"
renderdoc = "0.10"
schemars = "0.8"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
thiserror = "1.0"
uuid = {version = "0.8", features = ["serde", "v4"]}

[dev-dependencies]
approx = "0.5"

[target.'cfg(target_os = "android")'.dependencies]
jni = "0.18.0"
ndk = "0.4.0"
ndk-glue = "0.5"

[dev-dependencies.criterion]
features = ["html_reports"]
version = "0.3"

[[bench]]
harness = false
name = "transform_system"
